### ISSUE TITLE
http/https

### ISSUE THREAD

**Issue by aaryadev** [idevelop/ascii-camera#4]
Hi @idevelop 
These are awesome projects , neet update urls to https else they won't ask cam permission(Chrome)

Due  to Deprecating Powerful Features on Insecure Origins on chrome.
page throws " _getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details_ ."

**Comment by narendranss** [comment]
I am too kind of facing similar issue. I get this message "Please allow this page to access your camera." and in console I get the message pointed out by @aaryadev

**Comment by idevelop** [comment]
Thanks for flagging! Will update.

**Comment by idevelop** [comment]
Links in readme and repo info updated. Let me know if I missed anything. Thanks!
